# Basic Site Information
title: walterlv
author: walterlv
post_author: 吕毅
description: 吕毅的博客 walterlv's blog
mail: walter.lv@qq.com
about: .NET and Windows Developer, Microsoft MVP

# Site Appearance
logo: /assets/img/logo.png
icon: /favicon.ico
avatar:
  img: /assets/img/mvp.svg
  alt: Microsoft MVP
  url: https://mvp.microsoft.com/en-us/PublicProfile/5003225
  hint: 查看我的微软 MVP 主页
license:
  img: /assets/img/by-nc-sa.svg
default-theme: light
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Site Urls
baseurl: ""
url: "https://blog.walterlv.com"
links:
  - title: 博客
    url: /
  - title: 胡思乱想
    url: /mind
  - title: 朋友
    url: /friends
  - title: 开源项目
    url: /projects
  - title: 关于
    url: /about/
links-light:
  - icon: users
    title: 朋友
    url: /friends
  - icon: rss
    title: RSS
    url: /feed.xml

# Social Accounts
github:
  username: walterlv
  link: https://github.com/walterlv
facebook:
  username: Xblero
twitter:
  username: _lvyi_
stackoverflow:
  link: https://stackoverflow.com/users/6233938/walterlv

# Visit Analysis
analytics:
  google: UA-108101550-1
  cnzz: cnzz_stat_icon_1264408226
disqus:
  name: walterlv
  url: https://walterlv.com
gitment:
  owner: walterlv
  client_id: 9a8b44a07f269679e9b5
  client_secret: 3412cef75373074fd43b62462a7adef7ad1e2127
  repo: walterlv.github.io
leancloud:
  appid: 2NpLNUTfjU4ey5wOeWPPiXXL-gzGzoHsz
  appkey: OeA2qCtXi7ifv96UbMQ4J1kn

# Post Settings
excerpt_separator: ---
paginate: 30
per_page: 30
paginate_path: "/blog/page:num/"
collections:
  articles:
    output: true
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "吕毅"
      permalink: "/post/:title.html"
  - scope:
      path: "_articles"
      type: "articles"
    values:
      layout: "post"
      author: "吕毅"
      permalink: "/article/:title.html"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# Others
exclude: ['package.json', 'src', 'node_modules']
